<ClockRect>:
    canvas:
        Color:
            rgba: (1, 0, 0, 1)
        Rectangle:
            pos: self.pos
            size: self.size

<AniRect>:
    canvas:
        Color:
            rgba: (.5, .8, 1, 1)
        Rectangle:
            pos: self.pos
            size: self.size


<AniLayout>:
    ani_rect: ani_rect
    AniRect:
        id: ani_rect
        pos: 100, 100
        size: 100, 100
    ClockRect:
        pos: [100, 100]
        size: [100, 100]